name: country_icons
description: A flutter package with many country flag icons that you can use via the Image.asset method
version: 1.1.0
author: Sebastian Faujour <sf@bytepark.de>
homepage: https://www.bytepark.de

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependecies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  assets:
    - icons/flags/png/
    - icons/flags/png/2.5x/
    - icons/flags/svg/